Add cache folders to Chrome and Firefox targets
EricZimmerman/KapeFiles pull request #248
Opened 2020-08-29 13:39 UTC by nemesislvlup

2020-08-29 13:55 UTC, EricZimmerman commented
why do we want cache in with the main one? cache was left out to remove a lot of noise and small garbage files.

can you make a separate target called something like

BrowserCacche.tkape

with the sole purpose of pulling cache for all the browsers? that way it stays modular and people can include/exclude as they see fit

2020-08-29 14:19 UTC, Jil requested changes
The Chrome path is missing multiple profiles support

2020-08-29 14:19 UTC, Jil commented on Targets/Browsers/Chrome.tkape
> +        Path: C:\users\%user%\AppData\Local\Google\Chrome\User Data\Default\Cache\
Needs to support multiple profiles
```suggestion
        Path: C:\users\%user%\AppData\Local\Google\Chrome\User Data\*\Cache\
```

2020-08-30 07:30 UTC, nemesislvlup commented
> why do we want cache in with the main one? cache was left out to remove a lot of noise and small garbage files.
> 
> can you make a separate target called something like
> 
> BrowserCacche.tkape
> 
> with the sole purpose of pulling cache for all the browsers? that way it stays modular and people can include/exclude as they see fit

Well, the IE and Edge targets do include the caches...

2020-08-30 07:42 UTC, nemesislvlup commented
Added a new pull request that removes the Caches from Edge/IE tkapes and adds them for all browsers into a new tkape.

2020-08-31 14:50 UTC, merged

2020-08-31 14:50 UTC, EricZimmerman commented
Thanks for doing that. i think it will be a lot nicer to have the caches separate as it gives more targeted collection capabilities.